framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_transaction
        transports:
             sync:
                dsn: 'sync://'
                retry_strategy:
                    delay: 5000
             in-memory: 'in-memory://'
             async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            App\Messages\CreateOrderToPositionCommand: async
            App\Messages\EnrichOrderFromByBitCommand: sync
            App\Messages\ClosePositionCommand: async
when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                async: 'in-memory://'
                sync: 'in-memory://'
