framework:
    workflows:
        position:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Position
            initial_marking: Draft
            places:
                Draft:
                    name: Черновик
                Opened:
                    name: Открыта
                Closed:
                    name: Закрыта
            transitions:
                open:
                    from: [ Draft ]
                    to: Opened
                close:
                    from: [Opened, Draft]
                    to: Closed
        order:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Order
            initial_marking: New
            places:
                New:
                    name: Новый
                Filled:
                    name: Исполнен
                Cancelling:
                    name: Отменяется
                Cancelled:
                    name: Отменён
            transitions:
                fill:
                    from: [ New, Cancelling ]
                    to: Filled
                cancel:
                    from: [ New, Cancelling ]
                    guard: "subject.isNew()"
                    to: Cancelled
