framework:
    workflows:
        position:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Position
            initial_marking: BuyOrderFullFilled
            places:
                BuyOrderFullFilled:
                    name: Создан приказ на покупку
                SellOrderCreated:
                    name: Создан приказ на продажу
                Closed:
                    name: Закрыта
            transitions:
                to_sell_order_created:
                    from: [BuyOrderFullFilled]
                    to: SellOrderCreated
                close:
                    from: [BuyOrderFullFilled, SellOrderCreated]
                    to: Closed
        order:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Order
            initial_marking: New
            places:
                New:
                    name: Новый
                Filled:
                    name: Исполнен
                Cancelling:
                    name: Отменяется
                Cancelled:
                    name: Отменён
            transitions:
                fill:
                    from: [ New ]
                    to: Filled
                start_canceling:
                    from: [ New ]
                    to: Cancelling
                cancel:
                    from: [ Cancelling ]
                    to: Cancelled
