# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Bybit/'
            - '../src/**/Message/'
            - '../src/**/Model'
            - '../src/TradingStrategy/**/Strategy'
            - '../src/TradingStrategy/**/Event'
            - '../src/Kernel.php'
    ByBit\SDK\ByBitApi:
        arguments:
            $key: 'rMYSYkIoDbFrWY8cEU'
            $secret: 'S0BvBGFeqz6OsXIMJ7NxQt1FaAgNcuJQoSOg'
    App\TradingStrategy\TradingStrategyFactoryInterface:
        class: App\TradingStrategy\TradingStrategyFactory
    App\Market\Repository\CandleRepository:
        arguments:
#            $denormalizer: '@app.serializer.bybit'
            $marketApi:  '@=service("ByBit\\SDK\\ByBitApi").marketApi()'
#    app.serializer.bybit:
#        class: Symfony\Component\Serializer\Serializer
#        arguments:
#            $normalizers: ['@app.denormalizer.bybit.candle', '@app.normalizer.bybit.order', '@app.denormalizer.bybit.order', '@app.denormalizer.bybit.candles']
#            $encoders: ['@serializer.encoder.json']
#    app.denormalizer.bybit.candle:
#        class: App\Market\Serializer\Denormalizer\CandleDenormalizer
#    app.denormalizer.bybit.candles:
#        class: App\Market\Serializer\Denormalizer\CandleCollectionDenormalizer
#    app.denormalizer.bybit.order:
#        class: App\Serializer\Denormalizer\OrderDenormalizer
#    app.normalizer.bybit.order:
#        class: App\Serializer\Normalizer\OrderNormalizer
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
